
runtime: python39

env_variables:
  FLASK_ENV: production

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6